source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'LKVideoPlayerKit_Example' do
  pod 'LKVideoPlayer', :path => '../'
  pod 'NEDMacros', :git => 'git@gitlab.miguan.com:mobile-platform/NEDMacros-iOS.git', :branch => 'master'
  pod 'LookinServer', :configurations => ['Debug']
end
